spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    password: kbi*iHy*ubxyE-59FfER

deepseek:
  api-key: "sk-921b3f7385334db6a16a2a117614d56b"

embedding:
  api:
    api-key: "sk-76675e868d094fee9d8ed2c6b5e7efcc"